### ISSUE TITLE
radio button ?

### ISSUE THREAD

**Issue by MrAndreius** [MikeRogers0/PHP-HTML5-Form-class#5]
Have you thought about what type fields in INPUT, radio button,
attribute name - the same?

$myForm->setInputField(array('name'=>'your-name', 'value'=>1, 'id'=>1, 
                                                 'type'=>'radio'), 'Your Name', true);
$myForm->setInputField(array('name'=>'your-name', 'value'=>2, 'id'=>2, 
                                                 'type'=>'radio'), 'Your Name', true);
$myForm->setInputField(array('name'=>'your-name', 'value'=>3, 'id'=>3, 
                                                 'type'=>'radio'), 'Your Name', true);

**Comment by MikeRogers0** [comment]
Good shout - I'll get on it asap!

**Comment by MikevHoenselaar** [comment]
I solved it by replacing all $this->fields[$attr['name']] with $this->fields[]

And using:

``` php
if ($this->attr['type'] == 'radio' && isset($this->attr['value'])) {
   $this->html .= '&nbsp;'.$this->attr['value'];    
}
```

in getHtml() function to have a description of the radiobutton :-)

**Comment by MikevHoenselaar** [comment]
I decided this would a lot easier :-)

``` php
class radioField extends inputField{
    public $options;

    public function addOption($value, $description, $checked = false){
        if($this->attr['value'] == $value){
            $checked = true;
        }
        $this->options[$value] = array('value'=>$value, 'description'=>$description, 'checked'=>$checked);
    }

    public function getHTML(){
        unset($this->attr['value']); // Remove the value attr
        // Cycle through the options
        if(is_array($this->options)){foreach($this->options as $option => $values){

            $this->html .= '<div class="option"><input type="radio" value="'.$values['value'].'" '.form::getAttrs($this->attr).(($values['checked'] == false) ? '' : ' checked').'/>&nbsp;'.$values['description'].'</div>';

        }}

        $this->addWrapper();
        return $this->html;
    }
}
```

$radio = $myForm->setRadioField(array('name'=>'type_new', 'required'=>false), 'New or Existing test', true);
$radio->addOption('1', 'This is a new test that we still have to do');
$radio->addOption('2', 'This is a test we already did but want to document insights');

Hopefully you like it.
